"""
Django settings for test_app project.

Generated by 'django-admin startproject' using Django 2.1.13.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '@7p!n*sz^)8=ecq+782p(yo39w)q=ru4t3ep*j4y#*%0+mn)n9'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'api',
    'common',
   # 'debug_toolbar',
    'rest_framework',
    'django_filters',
    'django_celery_results',
]

MIDDLEWARE = [
 #   'debug_toolbar.middleware.DebugToolbarMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'test_app.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'test_app.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
    'default': {
	        'ENGINE': 'django.db.backends.mysql',
	        'NAME': 'enter',
	        'HOST': '172.31.224.189',
	        'PORT': 3306,
	        'USER': 'tang',
	        'PASSWORD': 'xxxxxx',
	        'CHARSET': 'utf8',
	        'TIME_ZONE': 'Asia/Shanghai',
    },
    'slave_1': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': 'enter',
            'HOST': '172.31.224.189',
            'PORT': 3308,
            'USER': 'root',
            'PASSWORD': 'xxxxxx',
            'CHARSET': 'utf8',
            'TIME_ZONE': 'Asia/Shanghai',
    },
    'slave_2': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': 'enter',
            'HOST': '172.31.224.189',
            'PORT': 3309,
            'USER': 'root',
            'PASSWORD': 'xxxxxx',
            'CHARSET': 'utf8',
            'TIME_ZONE': 'Asia/Shanghai',
    },
    'slave_3': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': 'enter',
            'HOST': '172.31.224.189',
            'PORT': 3310,
            'USER': 'root',
            'PASSWORD': 'xxxxxx',
            'CHARSET': 'utf8',
            'TIME_ZONE': 'Asia/Shanghai',
    },

}

# 数据库路由配置
DATABASE_ROUTERS = [
    'common.db_routers.MasterSlaveRouter',
]



CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': [
            'redis://172.31.224.189:6379/0',
        ],
        'KEY_PREFIX': 'spider',
        'OPTIONS': {
            'PASSWORD': 'xxxxxx',
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            'CONNECTION_POOL_KWARGS': {
                'max_connections': 2048,
            },
        }
    },
}


# 数据库路由配置
DATABASE_ROUTERS = [
    'common.db_routers.MasterSlaveRouter',
]

REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'rest_framework.schemas.coreapi.AutoSchema',
    # 配置默认页面大小
    'PAGE_SIZE': 10,
    # 配置默认的分页类
    'DEFAULT_PAGINATION_CLASS': 'api.helpers.CustomPagePagination',
    # # 配置默认的过滤和排序类
    # 'DEFAULT_FILTER_BACKENDS': (
    #     'django_filters.rest_framework.DjangoFilterBackend',
    #     'rest_framework.filters.OrderingFilter',
    # ),
    'DEFAULT_THROTTLE_CLASSES': (
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ),
    'DEFAULT_THROTTLE_RATES': {
        'anon': '30/min',
        'user': '10000/day',
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# 调试工具栏
DEBUG_TOOLBAR_CONFIG = {
    # 引入jquery库
    'JQUERY_URL': 'https://cdn.bootcss.com/jquery/3.4.1/jquery.min.js',
    # 工具栏是否折叠
    'SHOW_COLLAPSED': True,
    # 是否显示工具栏
    'SHOW_TOOLBAR_CALLBACK': lambda x: True,
}


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'zh-hans'
# LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/


STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]


# 拼接出images路劲
UPLOADFILES_DIRS1 = [os.path.join(STATICFILES_DIRS[0], 'images'), ][0]
# 拼接出用户上传的地址
UPLOADFILES_DIRS = [os.path.join(UPLOADFILES_DIRS1, 'user_upload'), ][0]

CELERY_STATUS = False

# 避免浏览器自作聪明推断内容类型
SECURE_CONTENT_TYPE_NOSNIFF = True

# 避免跨站脚本攻击
SECURE_BROWSER_XSS_FILTER = True

X_FRAME_OPTIONS = 'DENY'

